version: "3.8"

services:
    app:
        build: .
        container_name: backend-ticket-app
        environment:
            DATABASE_URL: postgresql://postgres:password@postgres:5432/ticketdb
            PORT: 4000
        ports:
            - "4000:4000"
        depends_on:
            postgres:
                condition: service_healthy

    postgres:
        container_name: postgres-ticket-app
        image: postgres:17-alpine3.21
        restart: always
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: password
            POSTGRES_DB: ticketdb
        ports:
            - "5434:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data

        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            interval: 10s
            timeout: 5s
            retries: 5

volumes:
    postgres_data:
